services:
  backend:
    build: !override
      context: ..
      dockerfile: ./tatami/backend/Dockerfile
    image: champion-tatami-backend:latest
    pull_policy: build
    ports:
      - "${BACKEND_PORT:-8001}:8000"

  frontend:
    build: !override
      context: ./frontend
      dockerfile: ./Dockerfile
    image: champion-tatami-frontend:latest
    pull_policy: build

  outbox:
    build: !override
      context: ./outbox
      dockerfile: ./Dockerfile
    image: champion-tatami-outbox:latest
    pull_policy: build

  db:
    ports: !override
      - "${POSTGRES_PORT:-5432}:5432"
