FROM node:22-alpine AS builder

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./

RUN npm install --force

COPY frontend .

RUN npm run build

FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app ./

CMD ["npm", "start"]
