[project]
name = "champion-domain"
version = "0.1.2"
description = ""
authors = [
    {name = "lyp1noff",email = "lyp1noff@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[dependency-groups]
dev = [
    "mypy>=1.17.0,<2.0.0",
    "ruff>=0.16.1,<0.17.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120
lint.select = ["E", "F", "I", "UP", "B", "SIM"]
lint.ignore = ["B008"]
fix = true

[tool.mypy]
python_version = "3.12"
strict = true
show_error_codes = true
