"""default values for Bracket

Revision ID: 22db92c32dc1
Revises: d8005fdfc93e
Create Date: 2025-07-28 03:58:49.215064

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22db92c32dc1"
down_revision: Union[str, None] = "d8005fdfc93e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # First, update existing NULL values with defaults
    op.execute("UPDATE brackets SET start_time = '09:00:00' WHERE start_time IS NULL")
    op.execute("UPDATE brackets SET tatami = 1 WHERE tatami IS NULL")
    op.execute("UPDATE brackets SET type = 'single_elimination' WHERE type IS NULL")

    # Then make columns NOT NULL
    op.alter_column("brackets", "start_time", existing_type=postgresql.TIME(), nullable=False)
    op.alter_column("brackets", "tatami", existing_type=sa.INTEGER(), nullable=False)

    # Set default value for type column
    op.alter_column(
        "brackets",
        "type",
        existing_type=sa.String(length=50),
        nullable=False,
        server_default="single_elimination",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("brackets", "tatami", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("brackets", "start_time", existing_type=postgresql.TIME(), nullable=True)
    # ### end Alembic commands ###
