"""match-type-in-bracket-match

Revision ID: 4676866bd7f7
Revises: ba485a35aa38
Create Date: 2025-08-31 17:33:51.526853

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4676866bd7f7"
down_revision: Union[str, None] = "ba485a35aa38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "bracket_matches", sa.Column("match_type", sa.String(length=20), nullable=False, server_default="MAIN")
    )
    op.execute("UPDATE bracket_matches SET match_type = 'MAIN'")
    op.alter_column("bracket_matches", "match_type", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bracket_matches", "match_type")
    # ### end Alembic commands ###
