"""added export_last_updated_at to Tournament

Revision ID: 4bb4ae80dbed
Revises: 72113a80975d
Create Date: 2025-04-26 17:53:58.395146

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bb4ae80dbed"
down_revision: Union[str, None] = "72113a80975d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tournaments", sa.Column("export_last_updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tournaments", "export_last_updated_at")
    # ### end Alembic commands ###
