"""add applications table

Revision ID: 5dd76feba4cb
Revises: 6b3780a08ed7
Create Date: 2025-06-06 13:59:44.533780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd76feba4cb'
down_revision: Union[str, None] = '6b3780a08ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uix_application_unique', 'applications', ['athlete_id', 'category_id', 'tournament_id'])
    op.drop_constraint('applications_tournament_id_fkey', 'applications', type_='foreignkey')
    op.drop_constraint('applications_athlete_id_fkey', 'applications', type_='foreignkey')
    op.drop_constraint('applications_bracket_id_fkey', 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'athletes', ['athlete_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('applications', 'bracket_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('bracket_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key('applications_bracket_id_fkey', 'applications', 'brackets', ['bracket_id'], ['id'])
    op.create_foreign_key('applications_athlete_id_fkey', 'applications', 'athletes', ['athlete_id'], ['id'])
    op.create_foreign_key('applications_tournament_id_fkey', 'applications', 'tournaments', ['tournament_id'], ['id'])
    op.drop_constraint('uix_application_unique', 'applications', type_='unique')
    op.drop_column('applications', 'category_id')
    # ### end Alembic commands ###
