"""add_group_id_to_brackets

Revision ID: 720e5c36d523
Revises: 3e00a8484e48
Create Date: 2025-07-15 02:23:06.449938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "720e5c36d523"
down_revision: Union[str, None] = "3e00a8484e48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("brackets", sa.Column("group_id", sa.Integer(), nullable=True))
    # Set default value for existing brackets
    op.execute("UPDATE brackets SET group_id = 1 WHERE group_id IS NULL")
    # Make the column not nullable after setting default values
    op.alter_column("brackets", "group_id", nullable=False)
    op.create_unique_constraint(
        "uix_tournament_category_group",
        "brackets",
        ["tournament_id", "category_id", "group_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_tournament_category_group", "brackets", type_="unique")
    op.drop_column("brackets", "group_id")
    # ### end Alembic commands ###
