"""initial migration

Revision ID: 72113a80975d
Revises: 
Create Date: 2025-04-26 17:51:22.425821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72113a80975d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bracket_participants_athlete_id', table_name='bracket_participants')
    op.drop_index('ix_bracket_participants_bracket_id', table_name='bracket_participants')
    op.drop_index('ix_brackets_category_id', table_name='brackets')
    op.drop_index('ix_brackets_tournament_id', table_name='brackets')
    op.drop_constraint('brackets_category_id_fkey', 'brackets', type_='foreignkey')
    op.create_foreign_key(None, 'brackets', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brackets', type_='foreignkey')
    op.create_foreign_key('brackets_category_id_fkey', 'brackets', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_brackets_tournament_id', 'brackets', ['tournament_id'], unique=False)
    op.create_index('ix_brackets_category_id', 'brackets', ['category_id'], unique=False)
    op.create_index('ix_bracket_participants_bracket_id', 'bracket_participants', ['bracket_id'], unique=False)
    op.create_index('ix_bracket_participants_athlete_id', 'bracket_participants', ['athlete_id'], unique=False)
    # ### end Alembic commands ###
