"""min and max age for category

Revision ID: c94337081108
Revises: 22db92c32dc1
Create Date: 2025-07-29 21:46:09.524117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c94337081108"
down_revision: Union[str, None] = "22db92c32dc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("min_age", sa.Integer(), nullable=True))
    op.add_column("categories", sa.Column("max_age", sa.Integer(), nullable=True))
    op.execute("UPDATE categories SET min_age = 1, max_age = 99")
    op.alter_column("categories", "min_age", nullable=False)
    op.alter_column("categories", "max_age", nullable=False)
    op.drop_column("categories", "age")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("categories", "max_age")
    op.drop_column("categories", "min_age")
    # ### end Alembic commands ###
