"""applications

Revision ID: d8005fdfc93e
Revises: 720e5c36d523
Create Date: 2025-07-27 19:08:10.855508

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8005fdfc93e"
down_revision: Union[str, None] = "720e5c36d523"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("applications", sa.Column("status", sa.String(length=20), nullable=True))
    op.add_column("applications", sa.Column("comment", sa.String(length=500), nullable=True))
    op.add_column("applications", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("applications", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "updated_at")
    op.drop_column("applications", "created_at")
    op.drop_column("applications", "comment")
    op.drop_column("applications", "status")
    # ### end Alembic commands ###
