"""strict_datatypes

Revision ID: 1a29e2a0467e
Revises: 9337f00d8598
Create Date: 2025-08-01 02:22:28.967406

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a29e2a0467e"
down_revision: Union[str, None] = "9337f00d8598"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # First, update any NULL timestamp values to current time
    op.execute("UPDATE applications SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE applications SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE athlete_coach_links SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE athlete_coach_links SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE athletes SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE athletes SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE brackets SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE brackets SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE categories SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE categories SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE coaches SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE coaches SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE matches SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE matches SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE tournaments SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE tournaments SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE users SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE users SET updated_at = NOW() WHERE updated_at IS NULL")

    # Now make the columns non-nullable
    op.alter_column("applications", "status", existing_type=sa.VARCHAR(length=20), nullable=False)
    op.alter_column("applications", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("applications", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column(
        "athlete_coach_links",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "athlete_coach_links",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("athletes", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("athletes", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("brackets", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("brackets", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("categories", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("categories", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("coaches", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("coaches", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("matches", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("matches", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("tournaments", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("tournaments", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("users", "role", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("users", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("users", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("users", "role", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("tournaments", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("tournaments", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("matches", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("matches", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("coaches", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("coaches", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("categories", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("categories", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("brackets", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("brackets", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("athletes", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("athletes", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column(
        "athlete_coach_links",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "athlete_coach_links",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("applications", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("applications", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("applications", "status", existing_type=sa.VARCHAR(length=20), nullable=True)
    # ### end Alembic commands ###
