"""refactoring

Revision ID: 3e00a8484e48
Revises: c753b78a5a9a
Create Date: 2025-07-13 19:10:25.915858

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e00a8484e48"
down_revision: Union[str, None] = "c753b78a5a9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_applications_athlete_id"), "applications", ["athlete_id"], unique=False)
    op.create_index(op.f("ix_applications_category_id"), "applications", ["category_id"], unique=False)
    op.create_index(op.f("ix_applications_tournament_id"), "applications", ["tournament_id"], unique=False)
    op.create_index(op.f("ix_athlete_coach_links_athlete_id"), "athlete_coach_links", ["athlete_id"], unique=False)
    op.create_index(op.f("ix_athlete_coach_links_coach_id"), "athlete_coach_links", ["coach_id"], unique=False)
    op.create_index(op.f("ix_bracket_matches_bracket_id"), "bracket_matches", ["bracket_id"], unique=False)
    op.create_index(op.f("ix_bracket_matches_match_id"), "bracket_matches", ["match_id"], unique=False)
    op.create_index(op.f("ix_bracket_participants_athlete_id"), "bracket_participants", ["athlete_id"], unique=False)
    op.create_index(op.f("ix_bracket_participants_bracket_id"), "bracket_participants", ["bracket_id"], unique=False)
    op.add_column("brackets", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("brackets", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_brackets_category_id"), "brackets", ["category_id"], unique=False)
    op.create_index(op.f("ix_brackets_tournament_id"), "brackets", ["tournament_id"], unique=False)
    op.add_column("categories", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("categories", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_matches_athlete1_id"), "matches", ["athlete1_id"], unique=False)
    op.create_index(op.f("ix_matches_athlete2_id"), "matches", ["athlete2_id"], unique=False)
    op.create_index(op.f("ix_matches_winner_id"), "matches", ["winner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_matches_winner_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_athlete2_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_athlete1_id"), table_name="matches")
    op.drop_column("categories", "updated_at")
    op.drop_column("categories", "created_at")
    op.drop_index(op.f("ix_brackets_tournament_id"), table_name="brackets")
    op.drop_index(op.f("ix_brackets_category_id"), table_name="brackets")
    op.drop_column("brackets", "updated_at")
    op.drop_column("brackets", "created_at")
    op.drop_index(op.f("ix_bracket_participants_bracket_id"), table_name="bracket_participants")
    op.drop_index(op.f("ix_bracket_participants_athlete_id"), table_name="bracket_participants")
    op.drop_index(op.f("ix_bracket_matches_match_id"), table_name="bracket_matches")
    op.drop_index(op.f("ix_bracket_matches_bracket_id"), table_name="bracket_matches")
    op.drop_index(op.f("ix_athlete_coach_links_coach_id"), table_name="athlete_coach_links")
    op.drop_index(op.f("ix_athlete_coach_links_athlete_id"), table_name="athlete_coach_links")
    op.drop_index(op.f("ix_applications_tournament_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_category_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_athlete_id"), table_name="applications")
    # ### end Alembic commands ###
