"""bracket day

Revision ID: ee60f1efb4bd
Revises: ba485a35aa38
Create Date: 2025-09-25 17:08:18.168648

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee60f1efb4bd"
down_revision: Union[str, None] = "ba485a35aa38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("brackets", sa.Column("day", sa.Integer(), nullable=True))
    op.execute("UPDATE brackets SET day = 1 WHERE day IS NULL")
    op.alter_column("brackets", "day", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("brackets", "day")
    # ### end Alembic commands ###
